name: asterisk
description: Idiomatic bindings to Asterisk's REST interface, allowing calls to be managed in Dart.
version: 0.2.0
repository: https://github.com/simolus3/asterisk.dart
topics:
  - asterisk
  - voip
  - sip
  - telephony

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.14.0
  pool: ^1.5.1
  weak_cache: ^2.1.1
  web_socket_channel: ^2.4.5

dev_dependencies:
  async: ^2.11.0
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  charcode: ^1.3.1
  json_serializable: ^6.8.0
  lints: ^3.0.0
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  test: ^1.24.0
